name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Install kubectl
        uses: azure/setup-kubectl@v3  

      - name: Install helm
        uses: azure/setup-helm@v4.2.0 

      - name: Update kubeconfig   
        run: |
          aws eks update-kubeconfig --region us-east-1 --name sockShop
          kubectl config set-context --current --namespace=sock-shop     

      - name: Apply manifest files
        run: kubectl apply -f manifest/.

      - name: Update helm charts
        run: helm repo update   

      - name: Install helm charts
        run: |
          helm upgrade --install certificate jetstack/cert-manager
          helm upgrade --install prometheus prometheus/kube-prometheus-stack
          helm upgrade --install ingress ingress-nginx/ingress-nginx

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
